---
title: "Neuromuscular Blocking Agents and Enteral Feeding"
output: github_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

## Inclusion Criteria

* Patients age 18 years and older
* Patients admitted to an intensive care unit at Memorial Hermann-TMC
* Paralytic infusions ≥24 hours with vecuronium, rocuronium, or cisatracurium
* Received tube feeds and paralytic drip concurrently
 
## Exclusion Criteria
* Patients requiring total parenteral nutrition at time of paralysis

## Data Collection

1. Patient demographics including
    * Age (years)
    * Weight  (kg)
    * Gender
    * Hospital length of stay
    * ICU length of stay
    * Scr on day of initiation of paralytic drip 
    * eGFR on day of initiation of paralytic drip
    * Mechanical ventilation start time
    * Mechanical ventilation end time
1. Vasopressor data
    * Vasopressor requirement (Y/N)
    * Vasopressor dose (in norepinephrine equivalence)
        - Minimum dose per day
        - Maximum dose per day
        - Mean dose per day
    * Hours per day on vasopressor
1. Paralytic data
    * Paralytic used (cisatracurium, vecuronium, or rocuronium)
    * Train-of-four score 
        - Median score
        - Interquartile range
    * Dose of paralytic used
    * Paralysis indication
    * TPN initiated during paralysis (Y/N)
        - If yes, what day of paralysis TPN was initiated
1. Serum Osmolality data
    * Measured serum osmolality initiation of tube feeds (if available)
    * Calculated serum osmolality at initiation of tube feeds
    * Serum Na at tube feed initiation
    * Serum glucose at tube feed initiation
    * Serum BUN at tube feed initiation
1. Enteral nutrition data
    * Feeding tube location
    * Enteral nutrition formulation
    * Enteral nutrition outcomes
        - Nutrition goal calculated by dietician
        - Total amount of tube feeds patient received per day
        - Residuals ≥500 mL (Y/N)
1. Intolerance (Y/N)
    * Reason for intolerance (see definition of intolerance)
